version: '3.9'

services:

  php:
    container_name: ${PHP_NAME}
    build:
      context: .
      args:
        TAG: ${PHP_TAG}
        MAILHOG_VERSION: ${MAILHOG_VERSION}
        NEWRELIC_VERSION: ${NEWRELIC_VERSION}
        NEWRELIC_LICENSE_KEY: ${NEWRELIC_LICENSE_KEY}
        NEWRELIC_APPLICATION_NAME: ${NEWRELIC_APPLICATION_NAME}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - default
    environment:
      ENV: ${ENV}
      COMPOSER_ALLOW_SUPERUSER: 1
      PHP_WITH_ALL_LOCALES: ${PHP_WITH_ALL_LOCALES}
      PHP_EXTRA_LOCALES: ${PHP_EXTRA_LOCALES}
      PHP_COMPOSER_PATH: ${PHP_COMPOSER_PATH}
      PHP_WP_CLI_ENABLED: ${PHP_WP_CLI_ENABLED}
      PHP_APCU_ENABLED: ${PHP_APCU_ENABLED}
      PHP_MCRYPT_ENABLED: ${PHP_MCRYPT_ENABLED}
      PHP_IMAGICK_ENABLED: ${PHP_IMAGICK_ENABLED}
      PHP_MAXMINDDB_ENABLED: ${PHP_MAXMINDDB_ENABLED}
      PHP_MONGODB_ENABLED: ${PHP_MONGODB_ENABLED}
      PHP_XDEBUG_ENABLED: ${PHP_XDEBUG_ENABLED}
      PHP_MEMCACHED_ENABLED: ${PHP_MEMCACHED_ENABLED}
      PHP_NEWRELIC_ENABLED: ${PHP_NEWRELIC_ENABLED}
      PHP_PDO_DBLIB_ENABLED: ${PHP_PDO_DBLIB_ENABLED}
      PHP_PDO_PGSQL_ENABLED: ${PHP_PDO_PGSQL_ENABLED}
      PHP_PGSQL_ENABLED: ${PHP_PGSQL_ENABLED}
      PHP_OPCACHE_ENABLED: ${PHP_OPCACHE_ENABLED}
      GITHUB_TOKEN: ${GITHUB_TOKEN}

  mailhog:
    container_name: ${MAILHOG_NAME}
    image: mailhog/mailhog:${MAILHOG_TAG:-latest}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - ${MAILHOG_SMTP_PORT}:1025
      - ${MAILHOG_HTTP_PORT}:8025
    networks:
      - default
